<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        img {
            width: 50px;
            height: 50px;
        }
    </style>
</head>

<body>

    <form action="" method="post">
        <input type="text" name="name">
        <input type="submit" name="submit">
    </form>

    <?php
    if (isset($message)) {


        // $arr = $message;
        // $str = "";
        // for ($i = 0; $i < count($arr) / 20; $i++) {

        //     // echo $arr[$i]->title;
        //     // echo "-->";
        //     // echo $arr[$i]->author_name[0];
        //     // echo $arr[$i]->cover_edition_key;
        //     // echo "<br>";

        //     $str .= '<div  class="row w-25 h-25">
        //    <div class="col   w-10 h-25">
        //        <img src="https://covers.openlibrary.org/b/olid/' . $arr[$i]->cover_edition_key . '.jpg" alt="">
        //        </div>
        //    <div class="col">' . $arr[$i]->author_name[0] . '</div>
        //    <div class="col">' . $arr[$i]->cover_edition_key . '</div>
        //     </div>';
        // }

        // echo $str;
    }


    ?>
    <div class="container">
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope="col">image</th>
                    <th scope="col">author name</th>
                    <th scope="col">title</th>
                    <th scope="col">btn</th>

                </tr>
            </thead>
            <tbody>



                <?php
                if (isset($message)) {


                    $arr = $message;






                    $str = "";
                    for ($i = 0; $i < count($arr); $i++) {

                        // echo $data[$i]->name;
                        $str .= '<tr>
   
      <td>   <img  class="img-fluid img-responsive"" src="https://covers.openlibrary.org/b/olid/' . $arr[$i]->cover_edition_key . '.jpg" alt=""></td>
      <td>' . $arr[$i]->author_name[0] . '</td>
      <td>' . $arr[$i]->title  . '</td>
      <td><a href="/home/detail?isbn='.$arr[$i]->isbn[0].'">preview</a> </td>
    
    </tr>';
                    }

                    echo $str;
                }

                ?>

<!-- https://openlibrary.org/works/OL20898961W/Fantastic_Mr._Fox?edition=ia%3A911 -->





    </div>



    <!-- <div class="row">
        <div class="col">
            < <img src="  https://covers.openlibrary.org/b/olid/" . $arr[$i]->cover_edition_key.jpg" alt="">/div>
                <div class="col">

                </div>
                <div class="col">

                </div>

        </div> -->


</body>

</html>