<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <?php


  // echo "gfdhfg";
  echo "<pre>";
  // print_r($message);
  // die();

  for ($i = 0; $i < count($message); $i++) {


    $date = $message[$i]->date;
    $forecast = $message[$i]->day;


    $str .= ' 
          <li class="list-group-item list-group-item-primary">' . $date . '</li><table class="table table-dark table-striped">
      <thead>
          <tr>
          </tr>
      </thead>
      <tbody>';
    foreach ($forecast as $key => $value) {

      if ($key != 'condition') {
        $str .= '<tr>
                                      
          <td>' . $key . ' </td>
          <td>' . $value . '</td>
          </tr>';
      }
    }
    $str .= '</table>';
  }






  echo $str;
  // die;





  ?>




  <div class=" container">


  </div>

</body>

</html>