<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<?php

if(isset($message)){

    $arr=$message;

    $count=1;

    for ($i = 0; $i < count($arr); $i++) {

        $obj=$arr[$i];
        echo $count++." -> ";
        foreach ($obj as $key => $value) {
            print "$key => $value\n";
            echo "<br>";
        }
        echo "<br>";
        echo "<br>";
     

    }

    
}


?>
    
</body>
</html>