<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

<div class="container">

<div >

    <?php



    if (isset($message)) {


        // echo "<pre>";

        // print_r($message);


        $str = '
              <div">
                
              <li class="list-group-item list-group-item-primary">Region -->'.$message->region.'</li>
              <li class="list-group-item list-group-item-primary">Time zone-->'.$message->tz_id.'</li>
              <li class="list-group-item list-group-item-primary">localtime--> '.$message->localtime.'</li>
           
              </div>';

        echo $str;
        // die;




    }




    ?>

</div>

    </div>

</body>

</html>